name: Create and publish gh-starred image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  STARRED_IMAGE_NAME: brighteyed/gh-starred

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: starred
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.STARRED_IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/starred/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.starred.outputs.tags }}
          labels: ${{ steps.starred.outputs.labels }}